Repository daechuyaza/brkt, pull requests merged in 2022-08, with the labels that each got.

#39 eslint import 관련 rule 추가
  .eslintrc.json
  src/pages/_app.tsx
Labels: 개발 환경

#41 article 상세 페이지 구현
  @types/emotion.d.ts
  mocks/handlers.ts
  mocks/server.ts
  src/common/ui/Button/Button.tsx
  src/common/ui/Marquee/Marquee.tsx
  src/common/ui/TextInput/TextInput.tsx
  src/components/about/Paragraph.tsx
  src/components/article/MainArticle.tsx
  src/modules/article/types/article.ts
  src/modules/article/types/index.ts
  src/modules/user/types/index.ts
  src/modules/user/types/user.ts
  src/pages/api/articles/index.ts
  src/pages/api/data/dto/GetArticleResponseDto.ts
  src/pages/api/data/mapper/mapGetArticlesResponseDtoToArticles.ts
  src/pages/api/data/model/Article.ts
  src/pages/api/repository/ArticleRepository.ts
  src/pages/articles.tsx
  src/pages/articles/[id].tsx
  src/pages/index.tsx
  src/styles/font.ts
Labels: 프론트엔드

#40 Simple git hooks + lint-staged + commitlint를 추가하였습니다.
  .commitlintrc.js
  .eslintignore
  lib/prisma.ts
  lint-staged.config.js
  package-lock.json
  package.json
  prisma/script.ts
  src/pages/_app.tsx
Labels: 개발 환경

#45 폰트 사이즈가 너무 커보이는 이슈 수정
  mocks/browser.ts
  mocks/handlers.ts
  next.config.js
  package-lock.json
  package.json
  src/common/assets/icons/DarkLogo.tsx
  src/common/assets/icons/DarkMode.tsx
  src/common/assets/icons/Search.tsx
  src/common/ui/Footer/Footer.tsx
  src/common/ui/Header/Navigator/Navigator.tsx
  src/common/ui/Layout/Layout.tsx
  src/common/ui/MainWideButton/MainWideButton.tsx
  src/common/ui/Marquee/Marquee.tsx
  src/components/article/MainArticle.tsx
  src/pages/index.tsx
  src/pages/subscribe/index.tsx
  src/styles/font.ts
Labels: 디자인 개선, 버그
